title: Morgane Rouvroy
description: My Personal Portfolio
author: Morgane Rouvroy
logo: /static/img/avatar.png
github: https://github.com/MorganeRouvroy
email: morgane.rouvroy@hotmail.com
about: Software Engineer, Query Planning and Optimization at Yellowbrick Data
 
google_analytics: UA-127727676-1

theme_skin: turquoise # blue turquoise green berry orange ceramic

baseurl: ""
url: ""

allowsearch: true

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
future: true
